include:
 - board: seeeduino_xiao_ble
   shield: KobitoKey_left rgbled_adapter
   snippet: zmk-usb-logging studio-rpc-usb-uart
   
 - board: seeeduino_xiao_ble
   shield: KobitoKey_right rgbled_adapter
   snippet: zmk-usb-logging

 - board: seeeduino_xiao_ble
   shield: settings_reset